const DATA=window.SEORAP_DATA;
const CHECK_KEY="seorap-progress-v3";
let checks=loadChecks();

function loadChecks(){try{return JSON.parse(localStorage.getItem(CHECK_KEY)||"{}")}catch{return {}}}
function saveChecks(){localStorage.setItem(CHECK_KEY,JSON.stringify(checks))}
function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c])}
function route(){const parts=location.hash.replace(/^#\/?/,"").split("/").filter(Boolean);if(parts[0]==="rules")return {view:"rules"};if(!parts.length||parts[0]==="home")return {view:"home"};return {view:parts[0],projectId:parts[1],sectionId:parts[2],categoryId:parts[3],groupId:parts[4]}}
function projectById(id){return DATA.projects.find(project=>project.id===id)}
function sectionById(id){return DATA.sections.find(section=>section.id===id)}
function categoryById(section,id){return section?.categories.find(category=>category.id===id)}
function groupById(category,id){return category?.groups?.find(group=>group.id===id)}
function projectTasks(project){return DATA.tasks.filter(task=>task.project===project.name)}
function scopedTasks(project,{sectionId,categoryId,groupId}={}){return projectTasks(project).filter(task=>(!sectionId||task.section===sectionId)&&(!categoryId||task.subsection===categoryId)&&(!groupId||task.group===groupId))}
function baseProgress(project,{sectionId,categoryId}={}){return Object.entries(DATA.completedBase||{}).reduce((sum,[key,count])=>{const [projectName,section,category]=key.split(":");return sum+(projectName===project.name&&(!sectionId||section===sectionId)&&(!categoryId||category===categoryId)?Number(count)||0:0)},0)}
function progress(project,scope={}){const tasks=scopedTasks(project,scope),base=baseProgress(project,scope),done=base+tasks.filter(task=>checks[task.id]).length;return {done,total:base+tasks.length,percent:base+tasks.length?Math.round(done/(base+tasks.length)*100):0}}
function progressLine(value){return `<span class="progress-count">${value.total?`${value.done}/${value.total}`:"0/0"}</span><span class="progress-bar"><i style="width:${value.percent}%"></i></span>`}
function href(...parts){return `#/${parts.filter(Boolean).join("/")}`}
function pageHead({eyebrow="MY PROJECTS",title,back="",progressValue=null}){return `<header class="page-head">${back?`<a class="back" href="${back}">←</a>`:""}<span><small>${esc(eyebrow)}</small><h1>${esc(title)}</h1></span>${progressValue?`<div class="head-progress">${progressLine(progressValue)}</div>`:""}</header>`}
function menuRow({title,emoji="📁",help="",url,value,emptyText="아직 작업 없음"}){return `<a class="menu-row" href="${url}"><em>${emoji}</em><span><b>${esc(title)}</b>${help?`<small>${esc(help)}</small>`:""}</span><span class="menu-progress">${value.total?`${value.done}/${value.total}`:emptyText}</span><i>›</i></a>`}

function renderHome(){return `${pageHead({title:"해야 할 것"})}<section class="project-list">${DATA.projects.map(project=>{const value=progress(project),emoji=project.id==="drawer-village"?"🗄️":"🎮";return `<a class="project-row" href="${href("project",project.id)}"><em>${emoji}</em><span><small>PROJECT</small><b>${esc(project.name)}</b></span><div><strong>${value.done}/${value.total}</strong><span class="progress-bar"><i style="width:${value.percent}%"></i></span></div><i>›</i></a>`}).join("")}</section><a class="rules-link" href="#/rules">공통 작업 규칙</a>`}
function renderProject(project){const value=progress(project);return `${pageHead({title:project.name,eyebrow:"PROJECT",back:"#/home",progressValue:value})}<section class="menu-list">${DATA.sections.map(section=>menuRow({title:section.label,emoji:section.emoji,url:href("section",project.id,section.id),value:progress(project,{sectionId:section.id})})).join("")}</section>`}
function renderSection(project,section){return `${pageHead({title:section.label,eyebrow:project.name,back:href("project",project.id),progressValue:progress(project,{sectionId:section.id})})}<section class="menu-list">${section.categories.map(category=>menuRow({title:category.label,emoji:category.emoji,url:href("category",project.id,section.id,category.id),value:progress(project,{sectionId:section.id,categoryId:category.id})})).join("")}</section>`}
function renderCategory(project,section,category){if(category.groups?.length)return `${pageHead({title:category.label,eyebrow:`${project.name} · ${section.label}`,back:href("section",project.id,section.id),progressValue:progress(project,{sectionId:section.id,categoryId:category.id})})}<section class="menu-list">${category.groups.map(group=>menuRow({title:group.label,emoji:group.emoji,url:href("group",project.id,section.id,category.id,group.id),value:progress(project,{sectionId:section.id,categoryId:category.id,groupId:group.id})})).join("")}</section>`;return renderTaskPage(project,section,category,null)}
function taskEmoji(task){if(task.section==="sound")return task.subsection==="scene-music"?"🎼":task.subsection==="food-sfx"?"🥄":task.subsection==="ambient-sfx"?"🌙":"🎙️";if(task.section==="art")return task.subsection==="building-exterior"?"🏘️":task.subsection==="home-exterior"?"🏠":task.subsection==="building-interior"?"🛋️":task.subsection==="preference-icons"?"🖌️":"🧩";return task.section==="release"?"🚀":task.section==="email"?"✉️":"📌"}
function taskRow(task){const checked=Boolean(checks[task.id]);return `<article class="task-row ${checked?"done":""}"><button class="task-open" data-open="${task.id}"><em>${taskEmoji(task)}</em><span><small>${task.direction?"그림 디렉팅":"할 일"}</small><b>${esc(task.title)}</b></span><i>›</i></button><button class="task-check ${checked?"checked":""}" data-check="${task.id}" aria-label="${esc(task.title)} 완료">${checked?"✓":"○"}</button></article>`}
function documentRow(document){return `<details class="document-row"><summary><span><small>붙여넣기용</small><b>${esc(document.title)}</b></span><i>＋</i></summary><div><p>${esc(document.description||"")}</p><textarea readonly>${esc(document.content)}</textarea><button class="copy" data-copy-document="${document.id}">내용 복사</button></div></details>`}
function renderTaskPage(project,section,category,group){const scope={sectionId:section.id,categoryId:category.id,groupId:group?.id},tasks=scopedTasks(project,scope),documents=(DATA.documents||[]).filter(document=>document.project===project.name&&document.section===section.id&&document.subsection===category.id);return `${pageHead({title:group?.label||category.label,eyebrow:`${project.name} · ${section.label}`,back:group?href("category",project.id,section.id,category.id):href("section",project.id,section.id),progressValue:progress(project,scope)})}<section class="compact-list">${documents.map(documentRow).join("")}${tasks.map(taskRow).join("")||(!documents.length?'<div class="empty">아직 등록된 작업이 없어요.</div>':"")}</section>`}
function directionHtml(task){return Object.entries(task.direction||{}).map(([key,value])=>{const title=DATA.directionLabels[key]||key,body=Array.isArray(value)?value.join(" · "):value;return `<article class="${key==="avoid"?"avoid":""}"><b>${esc(title)}</b><p>${esc(body)}</p></article>`}).join("")}
function templateSpec(task){
  if(task.section!=="art")return null;
  if(task.subsection==="building-interior")return {width:1600,height:900,name:"건물-내부-16x9",kind:"interior",label:"16:9 내부 배경"};
  if(task.subsection==="building-exterior"||task.subsection==="home-exterior")return {width:1024,height:1024,name:"건물-외관-정사각",kind:"building",label:"정사각 건물 외관"};
  if(task.subsection==="preference-icons")return {width:512,height:512,name:"취향사전-아이콘",kind:"icon",label:"투명 아이콘"};
  if(task.group==="ui-icons")return {width:2048,height:1024,name:"UI-아이콘-아틀라스",kind:"icons",label:"UI 아이콘 12칸"};
  if(task.group==="missing-sprites")return {width:1024,height:1024,name:"기본-스프라이트",kind:"sprite",label:"투명 스프라이트"};
  return {width:2048,height:2048,name:"종이-나무-UI-아틀라스",kind:"atlas",label:"메뉴·팝업 UI 아틀라스"};
}
function drawTemplate(spec,task){
  const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=spec.width;canvas.height=spec.height;
  ctx.fillStyle="#fffaf1";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#b99d7c";ctx.fillStyle="#5a4635";ctx.lineWidth=Math.max(2,canvas.width/512);ctx.font=`700 ${Math.max(18,canvas.width/55)}px sans-serif`;
  const box=(x,y,w,h,label)=>{ctx.setLineDash([16,12]);ctx.strokeRect(x,y,w,h);ctx.setLineDash([]);ctx.fillText(label,x+16,y+36)};
  ctx.fillText(`${task.title} · ${spec.width}×${spec.height}px`,40,55);
  if(spec.kind==="building"){box(112,120,800,760,"그림 안전 영역 800×760");ctx.beginPath();ctx.moveTo(112,800);ctx.lineTo(912,800);ctx.stroke();ctx.fillText("바닥선",128,842);box(312,215,400,260,"과장된 큰 상징물 자리");}
  else if(spec.kind==="interior"){box(80,90,1440,730,"배경 그림 전체 안전 영역");box(590,180,420,590,"캐릭터·행동이 올라갈 빈 자리");ctx.fillText("전경 소품은 좌우 아래쪽",90,865);}
  else if(spec.kind==="icon"){ctx.clearRect(0,0,512,512);ctx.strokeStyle="#b99d7c";ctx.fillStyle="#5a4635";ctx.font="700 20px sans-serif";box(46,46,420,420,"48px에서도 남을 중심 모양");ctx.beginPath();ctx.arc(256,256,180,0,Math.PI*2);ctx.stroke();}
  else if(spec.kind==="sprite"){ctx.clearRect(0,0,1024,1024);ctx.strokeStyle="#b99d7c";ctx.fillStyle="#5a4635";ctx.font="700 28px sans-serif";box(152,80,720,860,"투명 스프라이트 안전 영역");ctx.beginPath();ctx.moveTo(512,80);ctx.lineTo(512,940);ctx.moveTo(152,870);ctx.lineTo(872,870);ctx.stroke();}
  else if(spec.kind==="icons"){for(let row=0;row<2;row++)for(let col=0;col<6;col++)box(70+col*325,100+row*430,270,320,`${row*6+col+1} · 256px 아이콘`);}
  else{
    box(70,100,430,150,"기본 버튼 360×96");box(540,100,430,150,"선택 버튼 360×96");box(1010,100,430,150,"탭 320×96");box(1480,100,480,150,"게이지 420×64");
    box(70,310,900,620,"캐릭터 질문 팝업 900×620");box(1010,310,950,330,"현재 장면 카드 950×330");box(1010,680,950,250,"생활로그 행 950×180");
    for(let i=0;i<6;i++)box(70+i*315,990,265,250,`아이콘 슬롯 ${i+1}`);
    box(70,1300,600,620,"세로 메뉴 패널");box(710,1300,1250,300,"가로 메뉴·탭 레일");box(710,1640,590,300,"확인 팝업");box(1340,1640,620,300,"빈 상태 카드");
  }
  return canvas;
}
function downloadTaskTemplate(task){const spec=templateSpec(task);if(!spec)return;const canvas=drawTemplate(spec,task),link=document.createElement("a");link.download=`${spec.name}-${spec.width}x${spec.height}.png`;link.href=canvas.toDataURL("image/png");link.click()}
function openTask(id){const task=DATA.tasks.find(item=>item.id===id);if(!task)return;const dialog=document.querySelector("[data-task-dialog]"),checked=Boolean(checks[id]),template=templateSpec(task);dialog.querySelector("[data-task-detail]").innerHTML=`<section class="detail"><small>${taskEmoji(task)} ${esc(task.project)}</small><h1>${esc(task.title)}</h1><p>${esc(task.summary||"")}</p>${task.direction?`<section class="direction">${directionHtml(task)}</section>`:""}${template?`<button class="template-download" type="button" data-template-download="${id}">⬇️ PNG 백지 가이드 받기 · ${template.width}×${template.height}px</button>`:""}<div class="dialog-check"><b>${esc(task.checkLabel||"완료")}</b><button class="${checked?"checked":""}" data-check="${id}">${checked?"✓":"○"}</button></div></section>`;dialog.showModal()}
function renderRules(){return `${pageHead({title:"공통 작업 규칙",eyebrow:"DEFAULT RULES",back:"#/home"})}<section class="rules"><p>구체적인 현재 업데이트 내역이 아니라, 어떤 작업을 부탁해도 기본적으로 지켜야 할 원칙만 적어 두었습니다.</p><textarea class="prompt" readonly>${esc(DATA.gptPrompt)}</textarea><button class="copy" data-copy-prompt>프롬프트 복사</button></section>`}
function notFound(){return `${pageHead({title:"찾을 수 없어요",back:"#/home"})}<div class="empty">메뉴가 바뀌었거나 아직 준비되지 않은 항목이에요.</div>`}
function render(){const current=route();let html;if(current.view==="home")html=renderHome();else if(current.view==="rules")html=renderRules();else{const project=projectById(current.projectId),section=sectionById(current.sectionId),category=categoryById(section,current.categoryId),group=groupById(category,current.groupId);if(!project)html=notFound();else if(current.view==="project")html=renderProject(project);else if(current.view==="section"&&section)html=renderSection(project,section);else if(current.view==="category"&&section&&category)html=renderCategory(project,section,category);else if(current.view==="group"&&section&&category&&group)html=renderTaskPage(project,section,category,group);else html=notFound()}document.querySelector("#app").innerHTML=html;window.scrollTo({top:0,behavior:"instant"})}
function toggleCheck(id){checks[id]=!checks[id];saveChecks();const dialog=document.querySelector("[data-task-dialog]"),wasOpen=dialog?.open;render();if(wasOpen){dialog.close();openTask(id)}}
function copyText(value,button){navigator.clipboard.writeText(value).then(()=>{const old=button.textContent;button.textContent="복사했어요";setTimeout(()=>button.textContent=old,1300)}).catch(()=>{button.textContent="복사 실패"})}
document.addEventListener("click",event=>{const check=event.target.closest("[data-check]");if(check){event.stopPropagation();toggleCheck(check.dataset.check);return}const open=event.target.closest("[data-open]");if(open){openTask(open.dataset.open);return}const templateButton=event.target.closest("[data-template-download]");if(templateButton){const task=DATA.tasks.find(item=>item.id===templateButton.dataset.templateDownload);if(task)downloadTaskTemplate(task);return}const prompt=event.target.closest("[data-copy-prompt]");if(prompt){copyText(DATA.gptPrompt,prompt);return}const documentButton=event.target.closest("[data-copy-document]");if(documentButton){const document=DATA.documents.find(item=>item.id===documentButton.dataset.copyDocument);if(document)copyText(document.content,documentButton)}});
window.addEventListener("hashchange",render);render();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js?v=5").catch(()=>{}));
