const DATA=window.SEORAP_DATA;
const CHECK_KEY="seorap-progress-v3";
let checks=loadChecks();

function loadChecks(){try{return JSON.parse(localStorage.getItem(CHECK_KEY)||"{}")}catch{return {}}}
function saveChecks(){localStorage.setItem(CHECK_KEY,JSON.stringify(checks))}
function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c])}
function route(){const parts=location.hash.replace(/^#\/?/,"").split("/").filter(Boolean);if(parts[0]==="rules")return {view:"rules"};if(!parts.length||parts[0]==="home")return {view:"home"};return {view:parts[0],projectId:parts[1],sectionId:parts[2],categoryId:parts[3],groupId:parts[4]}}
function projectById(id){return DATA.projects.find(project=>project.id===id)}
function sectionById(id){return DATA.sections.find(section=>section.id===id)}
function categoryById(section,id){return section?.categories.find(category=>category.id===id)}
function groupById(category,id){return category?.groups?.find(group=>group.id===id)}
function projectTasks(project){return DATA.tasks.filter(task=>task.project===project.name)}
function scopedTasks(project,{sectionId,categoryId,groupId}={}){return projectTasks(project).filter(task=>(!sectionId||task.section===sectionId)&&(!categoryId||task.subsection===categoryId)&&(!groupId||task.group===groupId))}
function baseProgress(project,{sectionId,categoryId}={}){return Object.entries(DATA.completedBase||{}).reduce((sum,[key,count])=>{const [projectName,section,category]=key.split(":");return sum+(projectName===project.name&&(!sectionId||section===sectionId)&&(!categoryId||category===categoryId)?Number(count)||0:0)},0)}
function progress(project,scope={}){const tasks=scopedTasks(project,scope),base=baseProgress(project,scope),done=base+tasks.filter(task=>checks[task.id]).length;return {done,total:base+tasks.length,percent:base+tasks.length?Math.round(done/(base+tasks.length)*100):0}}
function progressLine(value){return `<span class="progress-count">${value.total?`${value.done}/${value.total}`:"0/0"}</span><span class="progress-bar"><i style="width:${value.percent}%"></i></span>`}
function href(...parts){return `#/${parts.filter(Boolean).join("/")}`}
function pageHead({eyebrow="MY PROJECTS",title,back="",progressValue=null}){return `<header class="page-head">${back?`<a class="back" href="${back}">←</a>`:""}<span><small>${esc(eyebrow)}</small><h1>${esc(title)}</h1></span>${progressValue?`<div class="head-progress">${progressLine(progressValue)}</div>`:""}</header>`}
function menuRow({title,help="",url,value,emptyText="아직 작업 없음"}){return `<a class="menu-row" href="${url}"><span><b>${esc(title)}</b>${help?`<small>${esc(help)}</small>`:""}</span><span class="menu-progress">${value.total?`${value.done}/${value.total}`:emptyText}</span><i>›</i></a>`}

function renderHome(){return `${pageHead({title:"해야 할 것"})}<section class="project-list">${DATA.projects.map(project=>{const value=progress(project);return `<a class="project-row" href="${href("project",project.id)}"><span><small>PROJECT</small><b>${esc(project.name)}</b></span><div><strong>${value.done}/${value.total}</strong><span class="progress-bar"><i style="width:${value.percent}%"></i></span></div><i>›</i></a>`}).join("")}</section><a class="rules-link" href="#/rules">공통 작업 규칙</a>`}
function renderProject(project){const value=progress(project);return `${pageHead({title:project.name,eyebrow:"PROJECT",back:"#/home",progressValue:value})}<section class="menu-list">${DATA.sections.map(section=>menuRow({title:section.label,url:href("section",project.id,section.id),value:progress(project,{sectionId:section.id})})).join("")}</section>`}
function renderSection(project,section){return `${pageHead({title:section.label,eyebrow:project.name,back:href("project",project.id),progressValue:progress(project,{sectionId:section.id})})}<section class="menu-list">${section.categories.map(category=>menuRow({title:category.label,url:href("category",project.id,section.id,category.id),value:progress(project,{sectionId:section.id,categoryId:category.id})})).join("")}</section>`}
function renderCategory(project,section,category){if(category.groups?.length)return `${pageHead({title:category.label,eyebrow:`${project.name} · ${section.label}`,back:href("section",project.id,section.id),progressValue:progress(project,{sectionId:section.id,categoryId:category.id})})}<section class="menu-list">${category.groups.map(group=>menuRow({title:group.label,url:href("group",project.id,section.id,category.id,group.id),value:progress(project,{sectionId:section.id,categoryId:category.id,groupId:group.id})})).join("")}</section>`;return renderTaskPage(project,section,category,null)}
function taskRow(task){const checked=Boolean(checks[task.id]);return `<article class="task-row ${checked?"done":""}"><button class="task-open" data-open="${task.id}"><span><small>${task.direction?"디렉팅 있음":"할 일"}</small><b>${esc(task.title)}</b></span><i>›</i></button><button class="task-check ${checked?"checked":""}" data-check="${task.id}" aria-label="${esc(task.title)} 완료">${checked?"✓":"○"}</button></article>`}
function documentRow(document){return `<details class="document-row"><summary><span><small>붙여넣기용</small><b>${esc(document.title)}</b></span><i>＋</i></summary><div><p>${esc(document.description||"")}</p><textarea readonly>${esc(document.content)}</textarea><button class="copy" data-copy-document="${document.id}">내용 복사</button></div></details>`}
function renderTaskPage(project,section,category,group){const scope={sectionId:section.id,categoryId:category.id,groupId:group?.id},tasks=scopedTasks(project,scope),documents=(DATA.documents||[]).filter(document=>document.project===project.name&&document.section===section.id&&document.subsection===category.id);return `${pageHead({title:group?.label||category.label,eyebrow:`${project.name} · ${section.label}`,back:group?href("category",project.id,section.id,category.id):href("section",project.id,section.id),progressValue:progress(project,scope)})}<section class="compact-list">${documents.map(documentRow).join("")}${tasks.map(taskRow).join("")||(!documents.length?'<div class="empty">아직 등록된 작업이 없어요.</div>':"")}</section>`}
function directionHtml(task){return Object.entries(task.direction||{}).map(([key,value])=>{const title=DATA.directionLabels[key]||key,body=Array.isArray(value)?value.join(" · "):value;return `<article class="${key==="avoid"?"avoid":""}"><b>${esc(title)}</b><p>${esc(body)}</p></article>`}).join("")}
function openTask(id){const task=DATA.tasks.find(item=>item.id===id);if(!task)return;const dialog=document.querySelector("[data-task-dialog]"),checked=Boolean(checks[id]);dialog.querySelector("[data-task-detail]").innerHTML=`<section class="detail"><small>${esc(task.project)}</small><h1>${esc(task.title)}</h1><p>${esc(task.summary||"")}</p>${task.direction?`<section class="direction">${directionHtml(task)}</section>`:""}<div class="dialog-check"><b>${esc(task.checkLabel||"완료")}</b><button class="${checked?"checked":""}" data-check="${id}">${checked?"✓":"○"}</button></div></section>`;dialog.showModal()}
function renderRules(){return `${pageHead({title:"공통 작업 규칙",eyebrow:"DEFAULT RULES",back:"#/home"})}<section class="rules"><p>구체적인 현재 업데이트 내역이 아니라, 어떤 작업을 부탁해도 기본적으로 지켜야 할 원칙만 적어 두었습니다.</p><textarea class="prompt" readonly>${esc(DATA.gptPrompt)}</textarea><button class="copy" data-copy-prompt>프롬프트 복사</button></section>`}
function notFound(){return `${pageHead({title:"찾을 수 없어요",back:"#/home"})}<div class="empty">메뉴가 바뀌었거나 아직 준비되지 않은 항목이에요.</div>`}
function render(){const current=route();let html;if(current.view==="home")html=renderHome();else if(current.view==="rules")html=renderRules();else{const project=projectById(current.projectId),section=sectionById(current.sectionId),category=categoryById(section,current.categoryId),group=groupById(category,current.groupId);if(!project)html=notFound();else if(current.view==="project")html=renderProject(project);else if(current.view==="section"&&section)html=renderSection(project,section);else if(current.view==="category"&&section&&category)html=renderCategory(project,section,category);else if(current.view==="group"&&section&&category&&group)html=renderTaskPage(project,section,category,group);else html=notFound()}document.querySelector("#app").innerHTML=html;window.scrollTo({top:0,behavior:"instant"})}
function toggleCheck(id){checks[id]=!checks[id];saveChecks();const dialog=document.querySelector("[data-task-dialog]"),wasOpen=dialog?.open;render();if(wasOpen){dialog.close();openTask(id)}}
function copyText(value,button){navigator.clipboard.writeText(value).then(()=>{const old=button.textContent;button.textContent="복사했어요";setTimeout(()=>button.textContent=old,1300)}).catch(()=>{button.textContent="복사 실패"})}
document.addEventListener("click",event=>{const check=event.target.closest("[data-check]");if(check){event.stopPropagation();toggleCheck(check.dataset.check);return}const open=event.target.closest("[data-open]");if(open){openTask(open.dataset.open);return}const prompt=event.target.closest("[data-copy-prompt]");if(prompt){copyText(DATA.gptPrompt,prompt);return}const documentButton=event.target.closest("[data-copy-document]");if(documentButton){const document=DATA.documents.find(item=>item.id===documentButton.dataset.copyDocument);if(document)copyText(document.content,documentButton)}});
window.addEventListener("hashchange",render);render();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js?v=4").catch(()=>{}));
