const DATA=window.SEORAP_DATA;
const PROGRESS_KEY="seorap-progress-v7";
const LEGACY_PROGRESS_KEY="seorap-progress-v3";
const historicalCompleted=DATA.historicalCompleted||{};
const defaultCompleted=new Set(DATA.completedTaskIds||[]);
function loadChecks(){try{const current=localStorage.getItem(PROGRESS_KEY),legacy=localStorage.getItem(LEGACY_PROGRESS_KEY),parsed=JSON.parse(current||legacy||"{}");return parsed&&typeof parsed==="object"?parsed:{}}catch{return {}}}
let checks=loadChecks();
function saveChecks(){try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(checks))}catch{}}
function isComplete(task){return Object.hasOwn(checks,task.id)?Boolean(checks[task.id]):Boolean(task.completed||defaultCompleted.has(task.id))}
function completedCount(tasks,{withHistory=false,project=null}={}){const checked=tasks.filter(isComplete).length,history=withHistory&&project?Number(historicalCompleted[project.name]||0):0;return Math.min(tasks.length,checked+history)}
function progressMarkup(tasks,options={}){const done=completedCount(tasks,options),total=tasks.length,percent=total?Math.round(done/total*100):0;return `<span class="progress-count"><b>${done}</b>/${total}</span><span class="progress-track" aria-label="${done}/${total} 완료"><i style="width:${percent}%"></i></span>`}
function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c])}
function route(){const parts=location.hash.replace(/^#\/?/,"").split("/").filter(Boolean);if(parts[0]==="rules")return {view:"rules"};if(parts[0]==="copy")return {view:"copy"};if(!parts.length||parts[0]==="home")return {view:"home"};return {view:parts[0],projectId:parts[1],sectionId:parts[2],categoryId:parts[3],groupId:parts[4]}}
function projectById(id){return DATA.projects.find(project=>project.id===id)}
function sectionById(id){return DATA.sections.find(section=>section.id===id)}
function categoryById(section,id){return section?.categories.find(category=>category.id===id)}
function groupById(category,id){return category?.groups?.find(group=>group.id===id)}
function projectTasks(project){return DATA.tasks.filter(task=>task.project===project.name)}
function scopedTasks(project,{sectionId,categoryId,groupId}={}){return projectTasks(project).filter(task=>(!sectionId||task.section===sectionId)&&(!categoryId||task.subsection===categoryId)&&(!groupId||task.group===groupId))}
function href(...parts){return `#/${parts.filter(Boolean).join("/")}`}
function pageHead({eyebrow="MY PROJECTS",title,back=""}){return `<header class="page-head">${back?`<a class="back" href="${back}">←</a>`:""}<span><small>${esc(eyebrow)}</small><h1>${esc(title)}</h1></span></header>`}
function menuRow({title,emoji="📁",help="",url,tasks=[]}){return `<a class="menu-row" href="${url}"><em>${emoji}</em><span><b>${esc(title)}</b>${help?`<small>${esc(help)}</small>`:""}${progressMarkup(tasks)}</span><i>›</i></a>`}

function renderHome(){const allTasks=DATA.tasks,allDone=DATA.projects.reduce((sum,project)=>sum+completedCount(projectTasks(project),{withHistory:true,project}),0),allPercent=allTasks.length?Math.round(allDone/allTasks.length*100):0;return `${pageHead({title:"나의 퀘스트 북"})}<section class="quest-hero"><span class="quest-seal">★</span><div><small>TOTAL PROGRESS</small><h2>오늘도 한 칸씩 완성 중</h2><p>완료한 작업도 O 표시로 계속 남아요.</p></div><strong>${allDone}/${allTasks.length}<small>${allPercent}%</small></strong></section><section class="project-list">${DATA.projects.map(project=>{const tasks=projectTasks(project),visual=project.id==="drawer-village"?'<img src="assets/drawer-village-logo.png" alt="서랍마을 로고">':'<em aria-hidden="true">🎮</em>';return `<a class="project-row ${project.id==="drawer-village"?"is-drawer-village":"is-otaku"}" href="${href("project",project.id)}"><span class="project-visual">${visual}</span><span class="project-copy"><small>PROJECT QUEST</small><b>${esc(project.name)}</b><i>${esc(project.description)}</i>${progressMarkup(tasks,{withHistory:true,project})}</span><strong>›</strong></a>`}).join("")}</section><nav class="home-tools"><a class="copy-shortcut" href="#/copy"><em>📋</em><span><small>QUICK COPY</small><b>복붙거리</b><i>이메일 답변을 바로 복사해요.</i></span><strong>›</strong></a><a class="rules-shortcut" href="#/rules"><em>📜</em><span><small>DEFAULT RULES</small><b>공통 작업 규칙</b></span><strong>›</strong></a></nav>`}
function updateHistory(project){if(project.id!=="drawer-village")return "";const updates=DATA.updates||[];return `<details class="update-history"><summary class="update-heading"><span><small>PATCH ARCHIVE</small><h2>서랍마을 업데이트 기록</h2></span><b>${updates.length}개 버전 <i>⌄</i></b></summary><div class="update-list">${updates.map(update=>`<details><summary><span><b>v${esc(update.version)}</b><small>빌드 ${esc(update.code)} · ${esc(update.date)}</small></span><i>＋</i></summary><ul>${update.items.map(item=>`<li>${esc(item)}</li>`).join("")}</ul></details>`).join("")}</div></details>`}
function renderProject(project){return `${pageHead({title:project.name,eyebrow:"PROJECT",back:"#/home"})}<section class="project-progress">${progressMarkup(projectTasks(project),{withHistory:true,project})}</section>${updateHistory(project)}<section class="menu-list">${DATA.sections.map(section=>menuRow({title:section.label,emoji:section.emoji,url:href("section",project.id,section.id),tasks:scopedTasks(project,{sectionId:section.id})})).join("")}</section>`}
function renderSection(project,section){return `${pageHead({title:section.label,eyebrow:project.name,back:href("project",project.id)})}<section class="menu-list">${section.categories.map(category=>menuRow({title:category.label,emoji:category.emoji,url:href("category",project.id,section.id,category.id),tasks:scopedTasks(project,{sectionId:section.id,categoryId:category.id})})).join("")}</section>`}
function renderCategory(project,section,category){if(category.groups?.length)return `${pageHead({title:category.label,eyebrow:`${project.name} · ${section.label}`,back:href("section",project.id,section.id)})}<section class="menu-list">${category.groups.map(group=>menuRow({title:group.label,emoji:group.emoji,url:href("group",project.id,section.id,category.id,group.id),tasks:scopedTasks(project,{sectionId:section.id,categoryId:category.id,groupId:group.id})})).join("")}</section>`;return renderTaskPage(project,section,category,null)}
function taskEmoji(task){if(task.section==="sound")return task.subsection==="scene-music"?"🎼":task.subsection==="food-sfx"?"🥄":task.subsection==="ambient-sfx"?"🌙":"🎙️";if(task.section==="art")return task.subsection==="building-exterior"?"🏘️":task.subsection==="home-exterior"?"🏠":task.subsection==="building-interior"?"🛋️":task.subsection==="village-background"?"🗺️":task.subsection==="preference-icons"?"🖌️":"🧩";return task.section==="release"?"🚀":task.section==="email"?"✉️":"📌"}
function taskRow(task){const done=isComplete(task);return `<article class="task-row ${done?"is-complete":""}"><button class="task-open" data-open="${task.id}"><em>${taskEmoji(task)}</em><span><small>${done?"완료한 작업":task.direction?"그림 디렉팅":"작업 자료"}</small><b>${esc(task.title)}</b></span><i>›</i></button><button class="task-check" type="button" data-check="${task.id}" aria-label="${done?"완료 취소":"완료 표시"}" aria-pressed="${done}">${done?"O":""}</button></article>`}
function documentRow(document){return `<details class="document-row"><summary><span><small>붙여넣기용</small><b>${esc(document.title)}</b></span><i>＋</i></summary><div><p>${esc(document.description||"")}</p><textarea readonly>${esc(document.content)}</textarea><button class="copy" data-copy-document="${document.id}">내용 복사</button></div></details>`}
function renderTaskPage(project,section,category,group){const scope={sectionId:section.id,categoryId:category.id,groupId:group?.id},tasks=scopedTasks(project,scope),documents=(DATA.documents||[]).filter(document=>document.project===project.name&&document.section===section.id&&document.subsection===category.id);return `${pageHead({title:group?.label||category.label,eyebrow:`${project.name} · ${section.label}`,back:group?href("category",project.id,section.id,category.id):href("section",project.id,section.id)})}<section class="list-progress">${progressMarkup(tasks)}</section><section class="compact-list">${documents.map(documentRow).join("")}${tasks.map(taskRow).join("")||(!documents.length?'<div class="empty">아직 등록된 자료가 없어요.</div>':"")}</section>`}
function directionHtml(task){return Object.entries(task.direction||{}).map(([key,value])=>{const title=DATA.directionLabels[key]||key,body=Array.isArray(value)?value.join(" · "):value;return `<article class="${key==="avoid"?"avoid":""}"><b>${esc(title)}</b><p>${esc(body)}</p></article>`}).join("")}
function templateSpec(task){
  if(task.section!=="art")return null;
  if(task.subsection==="village-background")return {width:1600,height:1760,name:"마을-배경-세로형",kind:"town-background",label:"세로형 마을 배경"};
  if(task.subsection==="building-interior")return {width:1600,height:900,name:"건물-내부-16x9",kind:"interior",label:"16:9 내부 배경"};
  if(task.subsection==="building-exterior"||task.subsection==="home-exterior")return {width:1024,height:1024,name:"건물-외관-정사각",kind:"building",label:"정사각 건물 외관"};
  if(task.subsection==="preference-icons")return {width:512,height:512,name:"취향사전-아이콘",kind:"icon",label:"투명 아이콘"};
  if(task.group==="ui-icons")return {width:2048,height:1024,name:"UI-아이콘-아틀라스",kind:"icons",label:"UI 아이콘 12칸"};
  if(task.group==="missing-sprites")return {width:1024,height:1024,name:"기본-스프라이트",kind:"sprite",label:"투명 스프라이트"};
  return {width:2048,height:2048,name:"종이-나무-UI-아틀라스",kind:"atlas",label:"메뉴·팝업 UI 아틀라스"};
}
function drawTemplate(spec,task){
  const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=spec.width;canvas.height=spec.height;
  ctx.fillStyle="#fffaf1";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#b99d7c";ctx.fillStyle="#5a4635";ctx.lineWidth=Math.max(2,canvas.width/512);ctx.font=`700 ${Math.max(18,canvas.width/55)}px sans-serif`;
  const box=(x,y,w,h,label)=>{ctx.setLineDash([16,12]);ctx.strokeRect(x,y,w,h);ctx.setLineDash([]);ctx.fillText(label,x+16,y+36)};
  ctx.fillText(`${task.title} · ${spec.width}×${spec.height}px`,40,55);
  if(spec.kind==="town-background"){box(70,100,1460,1580,"마을 배경 안전 영역");box(430,270,740,1120,"캐릭터·건물 아이콘이 올라갈 여백");ctx.beginPath();ctx.moveTo(800,100);ctx.lineTo(800,1680);ctx.stroke();ctx.fillText("큰 길·시선 중심축",820,145);ctx.fillText("랜드마크는 상단 또는 좌우에 크게",90,1730);}
  else if(spec.kind==="building"){box(112,120,800,760,"그림 안전 영역 800×760");ctx.beginPath();ctx.moveTo(112,800);ctx.lineTo(912,800);ctx.stroke();ctx.fillText("바닥선",128,842);box(312,215,400,260,"과장된 큰 상징물 자리");}
  else if(spec.kind==="interior"){box(80,90,1440,730,"배경 그림 전체 안전 영역");box(590,180,420,590,"캐릭터·행동이 올라갈 빈 자리");ctx.fillText("전경 소품은 좌우 아래쪽",90,865);}
  else if(spec.kind==="icon"){ctx.clearRect(0,0,512,512);ctx.strokeStyle="#b99d7c";ctx.fillStyle="#5a4635";ctx.font="700 20px sans-serif";box(46,46,420,420,"48px에서도 남을 중심 모양");ctx.beginPath();ctx.arc(256,256,180,0,Math.PI*2);ctx.stroke();}
  else if(spec.kind==="sprite"){ctx.clearRect(0,0,1024,1024);ctx.strokeStyle="#b99d7c";ctx.fillStyle="#5a4635";ctx.font="700 28px sans-serif";box(152,80,720,860,"투명 스프라이트 안전 영역");ctx.beginPath();ctx.moveTo(512,80);ctx.lineTo(512,940);ctx.moveTo(152,870);ctx.lineTo(872,870);ctx.stroke();}
  else if(spec.kind==="icons"){for(let row=0;row<2;row++)for(let col=0;col<6;col++)box(70+col*325,100+row*430,270,320,`${row*6+col+1} · 256px 아이콘`);}
  else{
    box(70,100,430,150,"기본 버튼 360×96");box(540,100,430,150,"선택 버튼 360×96");box(1010,100,430,150,"탭 320×96");box(1480,100,480,150,"게이지 420×64");
    box(70,310,900,620,"캐릭터 질문 팝업 900×620");box(1010,310,950,330,"현재 장면 카드 950×330");box(1010,680,950,250,"생활로그 행 950×180");
    for(let i=0;i<6;i++)box(70+i*315,990,265,250,`아이콘 슬롯 ${i+1}`);
    box(70,1300,600,620,"세로 메뉴 패널");box(710,1300,1250,300,"가로 메뉴·탭 레일");box(710,1640,590,300,"확인 팝업");box(1340,1640,620,300,"빈 상태 카드");
  }
  return canvas;
}
function downloadTaskTemplate(task){const spec=templateSpec(task);if(!spec)return;const canvas=drawTemplate(spec,task),link=document.createElement("a");link.download=`${spec.name}-${spec.width}x${spec.height}.png`;link.href=canvas.toDataURL("image/png");link.click()}
function openTask(id){const task=DATA.tasks.find(item=>item.id===id);if(!task)return;const dialog=document.querySelector("[data-task-dialog]"),template=templateSpec(task),done=isComplete(task);dialog.querySelector("[data-task-detail]").innerHTML=`<section class="detail"><small>${taskEmoji(task)} ${esc(task.project)}</small><h1>${esc(task.title)}</h1><p>${esc(task.summary||"")}</p>${task.direction?`<section class="direction">${directionHtml(task)}</section>`:""}${template?`<button class="template-download" type="button" data-template-download="${id}">⬇️ PNG 백지 가이드 받기 · ${template.width}×${template.height}px</button>`:""}<button class="dialog-check ${done?"on":""}" type="button" data-check="${id}">${done?"O 완료됨":"완료로 표시"}</button></section>`;if(!dialog.open)dialog.showModal()}
function renderRules(){return `${pageHead({title:"공통 작업 규칙",eyebrow:"DEFAULT RULES",back:"#/home"})}<section class="rules"><p>구체적인 현재 업데이트 내역이 아니라, 어떤 작업을 부탁해도 기본적으로 지켜야 할 원칙만 적어 두었습니다.</p><textarea class="prompt" readonly>${esc(DATA.gptPrompt)}</textarea><button class="copy" data-copy-prompt>프롬프트 복사</button></section>`}
function renderCopy(){return `${pageHead({title:"복붙거리",eyebrow:"EMAIL QUICK COPY",back:"#/home"})}<p class="copy-intro">실제로 들어올 법한 문의 예시를 보고, 상황에 맞는 이메일 답변만 복사하세요. 해결하지 않은 내용을 임의로 덧붙이지 않아요.</p><section class="copy-grid">${(DATA.copyTemplates||[]).map(template=>`<article class="copy-card"><header><em>${template.emoji}</em><span><small>예상 문의</small><b>${esc(template.title)}</b></span></header><p class="copy-question">${esc(template.question)}</p><div class="copy-replies">${template.replies.map(reply=>`<section><b>${esc(reply.label)}</b><textarea readonly>${esc(reply.content)}</textarea><button class="copy" type="button" data-copy-template="${template.id}" data-copy-language="${reply.code}">${esc(reply.label)} 답변 복사</button></section>`).join("")}</div></article>`).join("")}</section>`}
function notFound(){return `${pageHead({title:"찾을 수 없어요",back:"#/home"})}<div class="empty">메뉴가 바뀌었거나 아직 준비되지 않은 항목이에요.</div>`}
function render(){const current=route();let html;if(current.view==="home")html=renderHome();else if(current.view==="rules")html=renderRules();else if(current.view==="copy")html=renderCopy();else{const project=projectById(current.projectId),section=sectionById(current.sectionId),category=categoryById(section,current.categoryId),group=groupById(category,current.groupId);if(!project)html=notFound();else if(current.view==="project")html=renderProject(project);else if(current.view==="section"&&section)html=renderSection(project,section);else if(current.view==="category"&&section&&category)html=renderCategory(project,section,category);else if(current.view==="group"&&section&&category&&group)html=renderTaskPage(project,section,category,group);else html=notFound()}document.querySelector("#app").innerHTML=html;window.scrollTo({top:0,behavior:"instant"})}
function copied(button){const old=button.textContent;button.textContent="복사했어요";setTimeout(()=>button.textContent=old,1300)}
function copyText(value,button){if(legacyCopy(value)){copied(button);navigator.clipboard?.writeText?.(value).catch(()=>{});return}navigator.clipboard?.writeText?.(value).then(()=>copied(button)).catch(()=>button.textContent="복사 실패")}
function legacyCopy(value){const textarea=document.createElement("textarea");textarea.value=value;textarea.style.position="fixed";textarea.style.opacity="0";document.body.append(textarea);textarea.select();let success=false;try{success=document.execCommand("copy")}catch{}textarea.remove();return success}
document.addEventListener("click",event=>{const check=event.target.closest("[data-check]");if(check){event.preventDefault();event.stopPropagation();const task=DATA.tasks.find(item=>item.id===check.dataset.check);if(!task)return;const y=scrollY;checks[task.id]=!isComplete(task);saveChecks();const dialog=document.querySelector("[data-task-dialog]"),wasOpen=dialog?.open;render();scrollTo({top:y,behavior:"instant"});if(wasOpen)openTask(task.id);return}const open=event.target.closest("[data-open]");if(open){openTask(open.dataset.open);return}const templateButton=event.target.closest("[data-template-download]");if(templateButton){const task=DATA.tasks.find(item=>item.id===templateButton.dataset.templateDownload);if(task)downloadTaskTemplate(task);return}const prompt=event.target.closest("[data-copy-prompt]");if(prompt){copyText(DATA.gptPrompt,prompt);return}const documentButton=event.target.closest("[data-copy-document]");if(documentButton){const document=DATA.documents.find(item=>item.id===documentButton.dataset.copyDocument);if(document)copyText(document.content,documentButton);return}const templateCopy=event.target.closest("[data-copy-template]");if(templateCopy){const template=DATA.copyTemplates.find(item=>item.id===templateCopy.dataset.copyTemplate),reply=template?.replies?.find(item=>item.code===templateCopy.dataset.copyLanguage)||template?.replies?.[0];if(reply)copyText(reply.content,templateCopy)}});
window.addEventListener("hashchange",render);render();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js?v=18",{updateViaCache:"none"}).then(registration=>registration.update()).catch(()=>{}));
